export const APP_PATHS = {
    HOME: '/',
    SHOP: '/shop',
    PRODUCT_DETAILS: '/shop/products/:productId',
    CART: '/cart',
    WISHLIST: '/wishlist',
    SAVED: '/saved',
    MY_ORDERS: '/orders',
    ACCOUNT: '/account',
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    ERROR_400: '/error/400',
    ERROR_403: '/error/403',
    ERROR_404: '/error/404',
    ERROR_409: '/error/409',
    ERROR_429: '/error/429',
    ERROR_500: '/error/500',
    ERROR_503: '/error/503',
    ADMIN_ROOT: '/admin',
    OVERVIEW: '/admin/overview',
    USERS: '/admin/users',
    PRODUCTS: '/admin/products',
    ORDERS: '/admin/orders',
    CATEGORIES: '/admin/categories',
    IMAGES: '/admin/images',
    productDetails: (productId: number | string) => `/shop/products/${productId}`,
} as const
