# Generated by Kilo Code on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password_hash",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]

