# Generated by Django 4.2.28 on 2026-02-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0003_order_cancelled_at_order_currency_order_delivered_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("user", "idempotency_key"),
                name="uniq_order_user_idempotency_key_not_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("order", "idempotency_key"),
                name="uniq_payment_attempt_order_idempotency_key_not_null",
            ),
        ),
    ]
