# Generated by Django 4.2.28 on 2026-03-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0009_order_customer_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("customer", "Customer"), ("manager", "Manager"), ("admin", "Admin")],
                default="customer",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("suspended", "Suspended"), ("invited", "Invited")],
                default="active",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="UserInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.CharField(max_length=64, unique=True)),
                ("role", models.CharField(default="customer", max_length=16)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_invite",
                "indexes": [models.Index(fields=["expires_at"], name="user_invite_exp_idx")],
            },
        ),
    ]
