# Generated by Django 4.2.28 on 2026-03-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0010_admin_roles_invites"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="base_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="order",
            name="fx_rate",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10),
        ),
    ]
